services:
  redis:
    container_name: redis-asl
    image: redis:alpine
    volumes:
      - redis_data:/data/learn-asl
    ports:
      - "6379:6379"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus-asl
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../../etc/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-asl
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    depends_on:
      - prometheus

volumes:
  redis_data: