services:
  redis:
    container_name: redis-asl
    image: redis:alpine
    volumes:
      - redis_data:/data/learn-asl
    ports:
      - "6379:6379"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus-asl
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../../etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../../etc/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-asl
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager-asl
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ../../etc/alertmanager.yml:/etc/alertmanager/alertmanager.yml

volumes:
  redis_data:
  prometheus_data:
  grafana_data: