scrape_configs:
  - job_name: "spring-boot-logging"
    basic_auth:
      username: "prometheus"
      password: "ForASLOnly"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "Testing ASL Logging App"